
# Establecer la URL base de tu proyecto
baseURL = "https://anabmorales.github.io/portafolio-personal/"
#baseURL = 'http://localhost:1313'

languageCode = 'es-es'
title = 'Portfolio DWES'
theme='hyde'
# Configuración de la carpeta donde se generarán los archivos estáticos para GitHub Pages
publishDir = "docs"

[data]

[params]
   description = "Mi sitio con Hugo"
   themeColor = "theme-base-09"
   layoutReverse = true
   disqusShortname = "spf13"
[Menus]
main = [
      {Name = "1 Markdown", URL  = "/markdown/"},
      {Name = "2 Hobbies", URL  = "/hobbies/"},
      {Name = "3 Sección Técnica: PHP", URL  = "/tecnica/"},
      {Name = "4 Uso de Shortcodes", URL  = "/shortcodes/"},
      {Name = "5 Datos dinámicos", URL  = "/dinamico/"}      
]