
# Establecer la URL base de tu proyecto
baseURL = "https://anabmorales.github.io/portafolio-personal/"
#baseURL = 'http://localhost:1313'

languageCode = 'es-es'
title = 'Portfolio DWES'
theme='hyde'
# Configuración de la carpeta donde se generarán los archivos estáticos para GitHub Pages
publishDir = "docs"


[params]
   description = "Mi sitio con Hugo"
   themeColor = "theme-base-09"
   layoutReverse = true
   disqusShortname = "spf13"
[Menus]
main = [
      {Name = "Markdown", URL  = "/markdown/"},
      {Name = "Sección Técnica: PHP", URL  = "/tecnica/"},
      {Name = "Uso de Shortcodes", URL  = "/shortcodes/"},
      {Name = "Hobbies", URL  = "/hobbies/"}
]
