#baseURL = 'http://localhost:1313'
languageCode = 'es-es'
title = 'Portfolio DWES'
theme='hyde'
# Configuración de la carpeta donde se generarán los archivos estáticos para GitHub Pages
publishDir = "docs"

# Establecer la URL base de tu proyecto
baseURL = "https://anabmorales.github.io/portafolio-personal/"
[params]
   description = "Mi sitio con Hugo"
   themeColor = "theme-base-09"
   layoutReverse = true
   disqusShortname = "spf13"
[Menus]
main = [
      {Name = "Github", URL = "https://github.com/username/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
]
